import { Link } from 'react-router';
import './TermsPage.css';

const sections = [
  {
    title: '1. Eligibility',
    paragraphs: [
      'You must be at least 18 years of age, or the age of majority in your jurisdiction, to use RiverIQ. By using the Service, you represent that you meet these requirements.',
    ],
  },
  {
    title: '2. User Accounts',
    paragraphs: ['You are responsible for maintaining the confidentiality of your account credentials.', 'You agree to:'],
    items: [
      'Provide accurate information when creating your account.',
      'Keep your password secure.',
      'Notify us immediately of any unauthorized use of your account.',
      'Accept responsibility for all activity that occurs under your account.',
    ],
  },
  {
    title: '3. Subscription and Payments',
    paragraphs: [
      'Certain features of RiverIQ require a paid subscription.',
      'Subscriptions are billed in advance and renew automatically unless cancelled before the next billing date.',
      'Subscription fees are non-refundable except where required by applicable law.',
      'We reserve the right to change pricing at any time. Existing subscribers will be notified before any pricing changes take effect.',
    ],
  },
  {
    title: '4. Acceptable Use',
    paragraphs: ['You agree not to:'],
    items: [
      'Use the Service for any unlawful purpose.',
      'Attempt to gain unauthorized access to our systems.',
      'Reverse engineer, copy, or redistribute the Service.',
      'Upload malicious software or harmful content.',
      'Interfere with the operation or security of the Service.',
    ],
    closing: ['We reserve the right to suspend or terminate accounts that violate these Terms.'],
  },
  {
    title: '5. Hand History Uploads',
    paragraphs: [
      'RiverIQ allows users to upload poker hand history files for statistical analysis.',
      'You retain ownership of your uploaded files.',
      'By uploading files, you grant RiverIQ permission to process and analyze them solely for the purpose of providing the Service.',
      'You represent that you have the right to upload any files submitted.',
    ],
  },
  {
    title: '6. Intellectual Property',
    paragraphs: [
      'All software, designs, branding, logos, graphics, and content provided by RiverIQ remain the exclusive property of RiverIQ unless otherwise stated.',
      'You may not copy, reproduce, distribute, or create derivative works without prior written permission.',
    ],
  },
  {
    title: '7. Service Availability',
    paragraphs: [
      'While we strive to maintain reliable service, RiverIQ does not guarantee uninterrupted or error-free operation.',
      'Maintenance, updates, outages, or technical issues may temporarily affect availability.',
    ],
  },
  {
    title: '8. Disclaimer of Warranties',
    paragraphs: [
      'The Service is provided "AS IS" and "AS AVAILABLE."',
      'To the fullest extent permitted by law, RiverIQ disclaims all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement.',
      'RiverIQ does not guarantee the accuracy of poker statistics, calculations, or recommendations generated by the Service.',
    ],
  },
  {
    title: '9. Limitation of Liability',
    paragraphs: [
      'To the fullest extent permitted by law, RiverIQ and its owners, employees, and affiliates shall not be liable for any indirect, incidental, consequential, special, or punitive damages arising from your use of the Service.',
      'Our total liability for any claim relating to the Service shall not exceed the amount you paid to RiverIQ during the twelve (12) months preceding the claim.',
    ],
  },
  {
    title: '10. Account Suspension and Termination',
    paragraphs: ['We may suspend or terminate your account if:'],
    items: ['You violate these Terms.', 'You misuse the Service.', 'Your actions create security or legal risks.'],
    closing: ['You may delete your account at any time.'],
  },
  {
    title: '11. Privacy',
    paragraphs: [
      'Your use of RiverIQ is also governed by our Privacy Policy, which explains how we collect, use, and protect your information.',
    ],
  },
  {
    title: '12. Changes to These Terms',
    paragraphs: [
      'We may update these Terms from time to time.',
      'If we make material changes, we will notify users through the Service or by email where appropriate.',
      'Continued use of RiverIQ after updated Terms become effective constitutes acceptance of the revised Terms.',
    ],
  },
  {
    title: '13. Governing Law',
    paragraphs: [
      'These Terms are governed by the laws applicable in the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles.',
    ],
  },
  {
    title: '14. Contact',
    paragraphs: [
      'If you have any questions regarding these Terms, please contact us through the contact information provided on the RiverIQ website.',
    ],
  },
];

const TermsPage = () => {
  return (
    <main className='terms-page'>
      <article className='terms-document'>
        <Link className='terms-document__back' to='/features'>
          Back to features
        </Link>
        <header className='terms-document__header'>
          <h1>Terms of Service</h1>
          <p>Last Updated: July 20, 2026</p>
        </header>

        <section className='terms-document__intro' aria-label='Terms introduction'>
          <p>
            Welcome to RiverIQ ("RiverIQ", "we", "our", or "us"). These Terms of Service ("Terms") govern your
            access to and use of the RiverIQ website, applications, and services (collectively, the "Service").
          </p>
          <p>
            By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree to
            these Terms, you may not use the Service.
          </p>
        </section>

        {sections.map((section) => (
          <section className='terms-document__section' key={section.title}>
            <h2>{section.title}</h2>
            {section.paragraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
            {section.items && (
              <ul>
                {section.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            )}
            {section.closing?.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </section>
        ))}
      </article>
    </main>
  );
};

export default TermsPage;
